{% set name = "aioca" %}
{% set version = "1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aioca-{{ version }}.tar.gz
  sha256: 9eef22a95c47821fccf2e354c78f9bab7a0b0eda8190d4d56ee41b871662e252

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - epicscorelibs >=7.0.3.99.4.0
    - typing-extensions

test:
  imports:
    - aioca
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dls-controls/aioca
  summary: Asynchronous Channel Access client for asyncio and Python using libca via ctypes
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrakitin
