{% set name = "aioca" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aioca-{{ version }}.tar.gz
  sha256: 4d0bb637a0f9f7081cf0abaa8af10b66d50e3e8f7a6235d5fda9415a946703af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - epicscorelibs >=7.0.3.99.4.0
    - typing-extensions

test:
  imports:
    - aioca
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dls-controls/aioca
  summary: Asynchronous Channel Access client for asyncio and Python using libca via ctypes
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jwlodek
    - mrakitin
