{% set name = "aioca" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aioca-{{ version }}.tar.gz
  sha256: 463e2298cb22e00f8ca9fe6ce7bb6b80edb9225cc62e645590a70f3e05d91487

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - epicscorelibs >=7.0.3.99.4.0
    - typing-extensions

test:
  imports:
    - aioca
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dls-controls/aioca
  summary: Asynchronous Channel Access client for asyncio and Python using libca via ctypes
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrakitin
